### ISSUE TITLE
Publish to Nexus

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#1]
Please upload to nexus and let there be fame! ;)

**Comment by jackhumbert** [comment]
I'll upload it there eventually! For now, I'd like to keep it on Github only, as it's easier to manage issues and interact with people using it.

**Comment by Thortok** [comment]
Nexus allows the use of the vortex mod manager which makes it easier to install/remove the mod. You could put in the description to refer to github and then disable all posting/commenting on nexus so as not to have to manage two locations. I tried this mod for a little bit and then went to try to remove it and the game was crashing, probably cause I didn't remove everything correctly, and could only fix it by reinstalling the mod again. x.x

**Comment by jackhumbert** [comment]
Nexus release is up! https://www.nexusmods.com/cyberpunk2077/mods/5208/
