### ISSUE TITLE
Flight mode persistency between saves

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#12]
If save is loaded where you were flying: Car slams to the ground

**Comment by haywirephoenix** [comment]
Potential quick workaround: prevent saving while flying.

If it's possible, you could check if the player is driving and above a certain altitude on game start and activate flight mode accordingly, all contained within the mod?

**Comment by jackhumbert** [comment]
Checking for height above ground during load with raytracing seems like a pretty reasonable solution.

**Comment by jackhumbert** [comment]
Just pushed a version of this ([beea1c6](https://github.com/jackhumbert/let_there_be_flight/commit/beea1c65f0884baa786dccace81c2c46c41178a4)) if you want to grab the `build/` folder and test it!

**Comment by haywirephoenix** [comment]
What a legend. Testing.

**Comment by haywirephoenix** [comment]
It's working flawlessly

**Comment by jackhumbert** [comment]
Awesome, thanks for testing!
