### ISSUE TITLE
Roll needs binding for keyboard input

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#16]
Roll is missing. Not even displayed on the right as a hint

**Comment by jackhumbert** [comment]
It's currently mapped to a controller-only action - I'll create a custom one for it as well. Feel free to put your preference for the keys for this in #9

**Comment by oOXenonTitareOo** [comment]
> It's currently mapped to a controller-only action - I'll create a custom one for it as well. Feel free to put your preference for the keys for this in #9

Okay, well I just did there. Did I miss something?

**Comment by jackhumbert** [comment]
Should be possible to adjust in [v0.0.10](https://github.com/jackhumbert/let_there_be_flight/tree/v0.0.10)!
