### ISSUE TITLE
Adjusteable flight characteristics

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#17]
If you make the settings panel or use Native settings mod, than please let the user control the roll rate, pitch rate and top speed of flight. For me, the pitch rate is a bit too little.

PS: Sorry for literally BOMBING YOU on this repo. It's not intentional! :)

**Comment by jackhumbert** [comment]
Definitely! I'll also have an option to make it vehicle-dependent. Right now, all the vehicles pretty much "handle" the same, but there could be an option to let the smaller ones be more nimble, etc.

**Comment by jackhumbert** [comment]
Implemented through the Mod Settings menu.
