### ISSUE TITLE
Flight Mod gives me a Quickhack called "Lockey#......."

### ISSUE THREAD

**Issue by ZachiroEnigma0** [jackhumbert/let_there_be_flight#18]
2 things on this 
1. The Flight mod, as the title says gives me a new quickhack? Lockey#12238827325884734078 and when im in battle it sometimes interferes with my quickhacks, mainly Ping, on People
a FIX i found was re-equipping all of my quickhacks in a different order, but sometimes one of my quickhack slots is gone and that "Lockey#....." is there
im not sure whats going on with that 
2. "Lockey#12238827325884734078" specifically prevents you from using Ping on things like Cameras, and as stated above the only fix i found was requipping all of my quick hacks but it still happens after a while, it doesnt make "Lockey#12238827325884734078" go away, its still there. 
here is a screenshot 
![vlcsnap-2022-06-01-15h40m24s863](https://user-images.githubusercontent.com/62498718/171488880-1240ddb0-02c4-4146-ae13-01ff31917a3f.png)

**Comment by jackhumbert** [comment]
This was an experiment I never removed haha. I'll try to clean it up so it doesn't interfere with other systems!
