### ISSUE TITLE
Find a better UI hook for inkWidgets

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#2]
Dash doesn't show up with E3 hud, driving combat mod. Only enables itself when using a gun inside the car.

**Comment by jackhumbert** [comment]
The UI currently uses the persistent dot as a hook to display things - I'll figure out a workaround for this eventually. It isn't displayed when you load a save where you start in a vehicle (since the persistent dot isn't initialized).

**Comment by oOXenonTitareOo** [comment]
> The UI currently uses the persistent dot as a hook to display things - I'll figure out a workaround for this eventually. It isn't displayed when you load a save where you start in a vehicle (since the persistent dot isn't initialized).

Okay, sounds great! Yeah, I have noticed it.

**Comment by jackhumbert** [comment]
New hook in [v0.0.10](https://github.com/jackhumbert/let_there_be_flight/tree/v0.0.10) :)
