### ISSUE TITLE
missing "action button"

### ISSUE THREAD

**Issue by 4ngel0fVerdun** [jackhumbert/let_there_be_flight#22]
Hi, great Mod! having fun with it atm, just noticed the "f" action button is missing (I'm on PC) . this is not that big of a deal until I started...
- looting (can't see the item previews anymore when looting)
- missing dialog choices (the choices are "still" there but it seemed invisible or something since I can still choose)
- having trouble with which door I can open since the action button is missing.
![Screenshot (1193)](https://user-images.githubusercontent.com/107059861/172422433-6f0baf73-c13e-4c7b-9eb8-10a3167669e0.png)
![Screenshot (1194)](https://user-images.githubusercontent.com/107059861/172422452-d22b0abc-84cc-443c-ba95-5655c786846d.png)
![Screenshot (1195)](https://user-images.githubusercontent.com/107059861/172422542-b92132c3-8cb6-42d3-a07b-de0081de8a9c.png)
![Screenshot (1196)](https://user-images.githubusercontent.com/107059861/172423691-7f5aa7f4-09c5-4a3c-8873-91f549a107b4.png)

**Comment by jackhumbert** [comment]
I think this is related to force-exiting the vehicle at some point - it may be stuck in the vehicle flight context. It might also be related to the quickhack experiments, which will be removed in the next release.

**Comment by 4ngel0fVerdun** [comment]
> I think this is related to force-exiting the vehicle at some point - it may be stuck in the vehicle flight context. It might also be related to the quickhack experiments, which will be removed in the next release.

Hey! thanks for the response. The mod is great all in all don't get me wrong. As soon as I've heard about it, I immediately came back to the game lol. Thanks for the mod mate! cheers

**Comment by jackhumbert** [comment]
[I've just released a new version](https://github.com/jackhumbert/let_there_be_flight/releases) that may address this issue - could you give it a try if you have the chance?

**Comment by 4ngel0fVerdun** [comment]
hey, was about to test the game but got this message.

**Comment by 4ngel0fVerdun** [comment]
my bad i havent read ur instructions about upgrading the mod sorry mate
