### ISSUE TITLE
Sound of engines during flight is deafening.

### ISSUE THREAD

**Issue by Coyodee** [jackhumbert/let_there_be_flight#24]
For some cars, the sound of the engines during flight are beyond deafening. For contacts I keep most of my volumes at 30% with the only exception being the car radio at 100% so everything is kinda quiet with the exception of the radio. Till... I start flying and then the roar of the engines are so loud that I can't hear anything else and I have to turn down my speakers to the point of almost off because of how deafening the engine sounds are during flight and it's even worse if it happen to be a third party modded car. Those are even louder during flight to the point where I just have to turn the volume on my speakers off all together because those engine noises during flight are screamingly loud though I understand that's a mod on a mod and that's its own mess in and of itself. Please either turn down the volume of the engines or give us the option to turn down the volume. It's definitely starting to hurt my ears. I've tried everything on my end to adjust the volume of the cars engine noise during flight to no avail so please in the next update if possible adjust this.

**Comment by jackhumbert** [comment]
I'll try to hook up the volume to the game's fx volume. I need to do some measuring of the loudness to ensure that it's close to the other fx sounds as well.

**Comment by jackhumbert** [comment]
Just pushed a fix for this - you can download [this file](https://github.com/jackhumbert/let_there_be_flight/blob/main/build/r6/scripts/let_there_be_flight.reds) and replace `r6/scripts/let_there_be_flight.reds` - it pays attention to both Sfx & Master Volume.

**Comment by jackhumbert** [comment]
Closing this for now - let me know if you have any troubles!
