### ISSUE TITLE
UI flashing when turned off, in and out of flight

### ISSUE THREAD

**Issue by Dufresne240** [jackhumbert/let_there_be_flight#25]
When the UI is turned off, there are some white lines that seem to be the outline of the UI flashing every now and then. This happens even when I'm not flying the vehicle.

**Comment by jackhumbert** [comment]
I think this from the glitch effect - I should be able to turn it off when the UI is off.

**Comment by jackhumbert** [comment]
Just pushed a fix for this, I think - you can download [this file](https://github.com/jackhumbert/let_there_be_flight/blob/main/build/r6/scripts/let_there_be_flight.reds) to replace the one at `r6/scripts/let_there_be_flight.reds`.

**Comment by Dufresne240** [comment]
thank you!!
