### ISSUE TITLE
Strange first person camera when flying?

### ISSUE THREAD

**Issue by r0gler** [jackhumbert/let_there_be_flight#29]
It moves the camera more towards the center of the car and looking around feels weird too

**Comment by jackhumbert** [comment]
Is this in the hover & fly mode, or drone? I'm overriding camera movements in drone mode for the controller, but need to adjust it to still accept mouse camera movements.

**Comment by r0gler** [comment]
I've only tested it with the hover and fly mode so far, I'm also using an Xbox controller.

**Comment by jackhumbert** [comment]
This should be fixed in [1717dbe](https://github.com/jackhumbert/let_there_be_flight/commit/1717dbe4076d37328f92915b5fa5bcfd8473c975) :)

**Comment by jackhumbert** [comment]
Closing this, but if you notice it not working, let me know or re-open!
