### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by therealfroztee** [jackhumbert/let_there_be_flight#30]
Hi there. Not sure if it was error on my end, so to clarify it is packed.zip that we were supposed to unpack in the directory, right?
Github is generally confusing to me but I am hoping I got that right. 
After unpacking I am getting this error upon trying to start the game:

"Config version '1' is not supported (version < 0 or version > 0).

File: D:\GOG Galaxy\Ganes\Cyberpunk 2077\red4ext\config.ini

D:\a\RED4ext\src\red4ext.dll\Config.cpp:74

The game will close now to prevent unexpected behavior. "

I am really crossing my fingers that someone will know what the issue is, or that I installed the wrong thing so I can fix it. 
This mod looks so amazing and I really want to try it.

**Comment by r0gler** [comment]
I'm no dev for this mod, or for any mod but when I open my config.ini file located in the red4ext folder, the second line of text says "version = 0".

Judging by the error message you've sent here maybe try changing that value to 0 and see if it works? You should be able to right click on the config.ini and open it with notepad and change the value.

Hope this helps :)

**Comment by Thortok** [comment]
More than likely you did not install the prereq mods.
