### ISSUE TITLE
Visual bug with the Flight UI

### ISSUE THREAD

**Issue by r0gler** [jackhumbert/let_there_be_flight#31]
The 3D Flight UI will sometimes remain on the car when I'm not inside it and will sometimes turn into an advertisement too.

Clip of the bug - https://medal.tv/games/cyberpunk-2077/clips/odjE9eJNszvDX/d1337vqgBDra?invite=cr-MSxTNkIsNzAyOTI0NDIs

**Comment by haywirephoenix** [comment]
For anyone who wants the UI to default to off (until the mod has a settings menu).

r6\scripts\let_there_be_flight.reds go line 1310:

`this.showUI = false;`

**Comment by sphratrioth666** [comment]
There's another issue as well - if you turn the UI off, it still results in artifacts/visual bugs. Vertical, white lines randomly blinking on and off.

**Comment by titonix** [comment]
> There's another issue as well - if you turn the UI off, it still results in artifacts/visual bugs. Vertical, white lines randomly blinking on and off.

Happens to me aswell sometime

**Comment by jackhumbert** [comment]
This is all going to be reworked pretty soon, and the issues here will be addressed :)

**Comment by jackhumbert** [comment]
Should be resolved.
