### ISSUE TITLE
nothing happen when i hold R or square or X

### ISSUE THREAD

**Issue by orangpelupa** [jackhumbert/let_there_be_flight#33]
despite the release note says it will open a UI.

so how to make the car fly?

**Comment by orangpelupa** [comment]
the fly button is horn (click left stick). still nothing shown when holding r square x tho

**Comment by Marvillium** [comment]
I suggest changing the key mapping for "Flight_Options" and "Flight_UIToggle" to the same key (For example: O). It will help in enabling or disable the flight HUD outside the car with just a single button which seems to work flawlessly for me. You can also change the "Flight_Toggle" keybind to your own preference if you don't want it to be the same button as the horn.

**Comment by thunderpants** [comment]
I suggest getting a keyboard and mouse.

**Comment by Bartinga** [comment]
Which button on the PS controller activates the drone mode?

**Comment by Hyydro** [comment]
I've got the same issue. I can initiate hover mode just fine but the UI won't show and I can't use any of the other inputs. Mapping them to the same button also didn't fix it.

**Comment by orangpelupa** [comment]
> Which button on the PS controller activates the drone mode?

Which button in the keyboard do drone mode?

**Comment by Gwynevere** [comment]
Did you install all of the requirements ?

Requirements :

- [RED4ext](https://github.com/WopsS/RED4ext)
- [TweakXL](https://github.com/psiberx/cp2077-tweak-xl)
- [Input Loader](https://github.com/jackhumbert/cyberpunk2077-input-loader)
- [Redscript](https://github.com/jac3km4/redscript)
