### ISSUE TITLE
3d UI shows up when in NPC cars

### ISSUE THREAD

**Issue by titonix** [jackhumbert/let_there_be_flight#35]
As the title says, getting into NPC cars for quests shows the UI with the position and all that fancy stuff even if the cars not in flight mode.

**Comment by r0gler** [comment]
dev is aware of this bug and should hopefully be fixed in a future update.

In the meantime you can go to this file: 
r6\scripts\let_there_be_flight.reds 

go to line 1310 and change

>this.showUI = false;

**Comment by jackhumbert** [comment]
UI has been rehauled, and this shouldn't be an issue anymore.
