### ISSUE TITLE
game crashes when loading in

### ISSUE THREAD

**Issue by yes3445** [jackhumbert/let_there_be_flight#38]
when launching the game I get a message saying, "REDscript Compilation failed. The game will start but none of the scripts will take effect. this is caused by errors in: - let_there_be_flight.reds
you can try updating or removing these scripts to resolve the issue. If you need more information, consult the logs."

**Comment by sphratrioth666** [comment]
Usually, this is an issue when you're using an outdated REDscript or the mod is outdated itself. Happens after a new game patch release or when you play with 60+ mods like me, new REDscript comes out, some mods require the new version, you install it but other mods were not updated yet - then they become the cause of the problem. The message says LET THERE BE FLIGHT caused the error this time so by a logic of elimination - REDscript must be outdated for you. I have no problems myself while using both the newest REDscript and the newest mod from here - totally no issues at all.
