### ISSUE TITLE
Integrate In-Game Settings

### ISSUE THREAD

**Issue by sphratrioth666** [jackhumbert/let_there_be_flight#43]
Great job with a new mod.

Anyway, I figured out that the new command for inertia is `FlightSettings.SetFloat("yawDirectionalityFactor", 700.0)` so with "" and it still works but would it be possible to make it adjustable in a way? Native UI seems like a really convenient solution. I would be also happy even if you make an INI file where I can set it once and for all. Thanks in advance for a response. Great work with a new version anyway.

**Comment by jackhumbert** [comment]
I'm working on this now - it'll work/look similar to how [Native Settings](https://github.com/justarandomguyintheinternet/CP77_nativeSettings) does, but works on the backend through RED4ext, instead of through CET.

**Comment by sphratrioth666** [comment]
Ok, great. Thx a lot. It becomes a really, really cool mod with those thrusters, better controls, non-forced navigation and better UI. When UI errors are totally fixed and those flight settings become configurable - you are able to make it top 5 right behind CET, redscript and other frameworks :-D

**Comment by haywirephoenix** [comment]
> would it be possible to make it adjustable in a way?

Until the menu is finished, you can open `r6\scripts\let_there_be_flight.reds`, search the followinng:

`let yawDirectionality: Float = this.component.stats.d_speedRatio * FlightSettings.GetFloat(n"yawDirectionalityFactor");`

and add your desired value minus 50 like so:

`let yawDirectionality: Float = this.component.stats.d_speedRatio * FlightSettings.GetFloat(n"yawDirectionalityFactor") + 650.0 ;`

**Comment by sphratrioth666** [comment]
> > would it be possible to make it adjustable in a way?
> 
> Until the menu is finished, you can open `r6\scripts\let_there_be_flight.reds`, search the followinng:
> 
> `let yawDirectionality: Float = this.component.stats.d_speedRatio * FlightSettings.GetFloat(n"yawDirectionalityFactor");`
> 
> and add your desired value minus 50 like so:
> 
> `let yawDirectionality: Float = this.component.stats.d_speedRatio * FlightSettings.GetFloat(n"yawDirectionalityFactor") + 650.0;`

Works great! I did not think of opening the .reds file with a notepad, haha. Something interesting to learn. Thanks a lot for that - literally solves all the issues I had with the current version of a mod. I mean, the UI bugs are still a thing but a minor one.

**Comment by haywirephoenix** [comment]
Happy to help :) This is my all time favourite mod so it's great to be a part of it. 

To stop the UI from starting by default, see my comment here:

> 

https://github.com/jackhumbert/let_there_be_flight/issues/31#issuecomment-1155610021

If you're talking about the floating glitch effect, search "glitch" and put a // at the start of every line that comes up. You may need something more better suited than notepad too see the lines clearer such as VScode

**Comment by sphratrioth666** [comment]
> a //

Turning the UI off was quite simple but I do not really understand that part about glitching. I am referring a situation when the UI is off, even in driving mode, but the UI glitching starts on impact. This happens both in flight and on the ground. I can understand it happening with the UI on but when it's turned off - the glitching makes no sense and is extremely irritating :-P

However, I am nto able to understand this // thing at the beginning of every line where it comes up. Literally every line showing any result for a word "glitch" should start with // ? I am assuming that // marks a comment/label type of code, not the executable one so by doing that, I am turning the real code lines into a label/comment. Will it be fine with literally every line including a word "glitch"?

**Comment by haywirephoenix** [comment]
>  I am assuming that // marks a comment/label type of code

Yep that's correct, Try first by commenting this line like so ` // this.PlayLibraryAnimation(n"glitch");`

**Comment by sphratrioth666** [comment]
> > I am assuming that // marks a comment/label type of code
> 
> Yep that's correct, Try first by commenting this line like so ` // this.PlayLibraryAnimation(n"glitch");`

Sadly, it did not help. When I have a HUD off it still glitches out at impact on anything.

**Comment by jackhumbert** [comment]
> Sadly, it did not help. When I have a HUD off it still glitches out at impact on anything.

Are you using the latest code from the `build/` folder on Github? I pushed a fix for the UI glitching last week, I think.

**Comment by sphratrioth666** [comment]
> > Sadly, it did not help. When I have a HUD off it still glitches out at impact on anything.
> 
> Are you using the latest code from the `build/` folder on Github? I pushed a fix for the UI glitching last week, I think.

Yeah, you were right. Haha, sorry. I had one from 0.0.10. Now it works perfectly without glitching and I am still able to edit the jawdirectionality factor by adding +650 at the end :-D

**Comment by jackhumbert** [comment]
Implemented with [Mod Settings](https://github.com/jackhumbert/mod_settings).
