### ISSUE TITLE
Bugs with mods

### ISSUE THREAD

**Issue by oOXenonTitareOo** [jackhumbert/let_there_be_flight#7]
I cannot aim with my gun (vehicle combat mod) if flight mode on and car is not a car.

Mode switching is janky. Why on F if that's the exit button? :D I couldn't even find it in the inputs file.

Compatiblity issue: Function + mouse scroll. Scroll brings out gun with vehicle combat mod.

Sound bug: If pause (esc) pressed mod sounds are still being played, looped.

If save is loaded where you were flying: Car slams to the ground

AI cars on the road randomly enable flight mode for themselves, wreaking havock and chaos.

Car's camera sometimes stuck with No Camera Auto Centering mod so player cannot see where he's headed.

**Comment by jackhumbert** [comment]
Feel free to make individual issues for these! I can close each when they're addressed.
